name: conda_py3.7-tf2
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=51_gnu
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_4
  - backports.functools_lru_cache=2.0.0=pyhd8ed1ab_0
  - blas=1.0=openblas
  - ca-certificates=2025.12.2=hd43f75c_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - debugpy=1.5.1=py37had24c86_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - fftw=3.3.10=he4c0aac_0
  - ipykernel=6.16.2=pyh210e3f2_0
  - ipython=7.33.0=py37hd9ded2f_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - joblib=1.1.1=py37hd43f75c_0
  - jupyter_client=7.3.4=pyhd8ed1ab_0
  - jupyter_core=4.11.2=py37hd43f75c_0
  - ld_impl_linux-aarch64=2.40=h48e3ba3_0
  - libffi=3.4.4=h419075a_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h6e398d7_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libopenblas=0.3.30=h90745d9_2
  - libsodium=1.0.18=hb9de7d4_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libxcb=1.17.0=hf66535e_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - ncurses=6.5=h419075a_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - numpy-base=1.21.5=py37h4a83355_3
  - openssl=1.1.1w=h2f4d8fa_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=22.3.1=py37hd43f75c_0
  - prompt-toolkit=3.0.48=pyha770c72_0
  - psutil=5.9.0=py37hcd4c3ab_0
  - pthread-stubs=0.3=hfd63f10_1
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - python=3.7.16=h89984f6_0
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python_abi=3.7=2_cp37m
  - pyzmq=23.0.0=py37h7cb28e0_0
  - readline=8.3=h886d1d0_0
  - scikit-learn=1.0.2=py37h839d321_1
  - scipy=1.7.3=py37h8708280_2
  - setuptools=65.6.3=py37hd43f75c_0
  - sqlite=3.50.2=h998d150_1
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.15=h987d8db_0
  - tornado=6.1=py37heeccf27_3
  - traitlets=5.9.0=pyhd8ed1ab_0
  - wcwidth=0.2.10=pyhd8ed1ab_0
  - wheel=0.38.4=py37hd43f75c_0
  - xorg-libx11=1.8.12=hf66535e_1
  - xorg-libxau=1.0.12=hf66535e_0
  - xorg-libxdmcp=1.1.5=hf66535e_0
  - xorg-xorgproto=2024.1=h998d150_1
  - xz=5.6.4=h998d150_1
  - zeromq=4.3.4=h01db608_1
  - zlib=1.2.13=h998d150_1
  - pip:
      - absl-py==2.1.0
      - astunparse==1.6.3
      - cachetools==5.5.2
      - charset-normalizer==3.4.3
      - cycler==0.11.0
      - flatbuffers==25.2.10
      - fonttools==4.38.0
      - gast==0.4.0
      - google-auth==2.40.3
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.62.3
      - h5py==3.8.0
      - idna==3.10
      - importlib-metadata==6.7.0
      - keras==2.11.0
      - kiwisolver==1.4.5
      - libclang==18.1.1
      - markdown==3.4.4
      - markupsafe==2.1.5
      - matplotlib==3.5.3
      - numpy==1.21.6
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - packaging==24.0
      - pandas==1.3.5
      - pillow==9.5.0
      - protobuf==3.19.6
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pyparsing==3.1.4
      - pytz==2025.2
      - requests==2.31.0
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - six==1.17.0
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.11.0
      - tensorflow-cpu-aws==2.11.0
      - tensorflow-estimator==2.11.0
      - tensorflow-io==0.29.0
      - tensorflow-io-gcs-filesystem==0.29.0
      - termcolor==2.3.0
      - typing-extensions==4.7.1
      - urllib3==2.0.7
      - werkzeug==2.2.3
      - wrapt==1.16.0
      - zipp==3.15.0
prefix: /home/kongli/anaconda3/envs/conda_py3.7-tf2
